# apiVersion: v2
# name: dependency-example
# appVersion: "1.0"
# description: A Demo Helm chart for dependencies test
# version: 1.0.0
# dependencies:
#   - name: nginx
#     version: 8.3.0
#     repository: https://charts.bitnami.com/bitnami
#   - name: wordpress
#     version: 10.4.4
#     repository: https://charts.bitnami.com/bitnami

# apiVersion: v2
# name: dependency-example
# appVersion: "1.0"
# description: A Demo Helm chart for dependencies test
# version: 1.0.0
# dependencies:
#   - name: nginx
#     version: 8.3.0
#     repository: "@bitnami"
#   - name: wordpress
#     version: 10.4.4
#     repository: "@bitnami"

apiVersion: v2
name: dependency-example
appVersion: "1.0"
description: A Demo Helm chart for dependencies test
version: 1.0.0
dependencies:
  - name: nginx
    version: 8.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
    tags:
      - nginx
      - front-end
  - name: mysql
    version: 8.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
    tags:
      - mysql
      - back-end