apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
    # image: "{{ .Values.image.name }}: {{ required "A valid .Values.image.tag entry required!" .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports: 
    - containerPort: 80
    
