apiVersion: v1
kind: Service
metadata:
  name: {{ include "connectedfactory.fullname" . }}
  labels:
    name: {{ include "connectedfactory.fullname" . }}
spec:
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}



